### ISSUE TITLE
Error after upgrading theme: Failed to render "home"

### ISSUE THREAD

**Issue by sarru1291** [hossainemruz/toha#100]
I started building the site in August and after months, today I thought to update but encountered error after I synced `toha` theme to the latest commit.

```
Error: Error building site: failed to render pages: render of "home" failed: 
```
`~/Desktop/Github/sarru1291.github.io/themes/toha/layouts/index.html:45:18": execute of template failed: template: index.html:45:18: executing "index.html" at <partial (printf "sections/%s.html" (replace (lower .section.id) " " "-")) .>: error calling partial: partial "sections/.html" not found`

**Comment by hossainemruz** [comment]
Now, you have to provide id for a section.
https://www.github.com/hossainemruz/toha/tree/master/exampleSite%2Fdata%2Fen%2Fsections%2Fexperiences.yaml

**Comment by sarru1291** [comment]
Thanks, a lot of things have changed. I've configured everything now.
