### ISSUE TITLE
Multilanguage Content how to?

### ISSUE THREAD

**Issue by ranrinc** [hossainemruz/toha#101]
I manage to have this theme running with multilanguage. However making a posts a different story altogether, nothing works well at least the recent post appear on the English version. But posts link just doesn't works. I have tried multi variations without such luck. Maybe some help?

You can see my code at https://github.com/tirtadji-com/tirtadji-com.github.io

Need to get more information on the structures.

Also adding `id.toml` to the list

**Comment by ranrinc** [comment]
Manage to fixed the posts and now both languages can start, however, the recent post only shows 1. Unsure why?

**Comment by alex-bezek** [comment]
Hey @ranrinc, I've downloaded and ran your project
![image](https://user-images.githubusercontent.com/8029578/97067249-8326e800-1589-11eb-9e36-340470c03ae3.png)
I do see a single post as well. However, looking at your config that's what I would expect

![image](https://user-images.githubusercontent.com/8029578/97067275-c3866600-1589-11eb-85d6-b886bab0576c.png)

My understanding is that with hugo i18n all posts/content are isolated within their own locales. Let me know if i'm missing something or misunderstanding your issue.

**Comment by ranrinc** [comment]
> Hey @ranrinc, I've downloaded and ran your project
> ![image](https://user-images.githubusercontent.com/8029578/97067249-8326e800-1589-11eb-9e36-340470c03ae3.png)
> I do see a single post as well. However, looking at your config that's what I would expect
> 
> ![image](https://user-images.githubusercontent.com/8029578/97067275-c3866600-1589-11eb-85d6-b886bab0576c.png)
> 
> My understanding is that with hugo i18n all posts/content are isolated within their own locales. Let me know if i'm missing something or misunderstanding your issue.

Hi @alex-bezek thanks for the help.. I actually manage to have both language up and running hahahaha... just need to read hugo document a little bit longer in order to have it working

**Comment by alex-bezek** [comment]
awesome! glad it worked out for you @ranrinc
