### ISSUE TITLE
404 Icon isn't configurable

### ISSUE THREAD

**Issue by alex-bezek** [hossainemruz/toha#103]
The main site's logo is configurable via the site params object, however, the 404 partial doesn't use the config properly and falls back to the default
![image](https://user-images.githubusercontent.com/8029578/96390523-12e02700-1183-11eb-9d44-c86fd9fb1b0b.png)
![image](https://user-images.githubusercontent.com/8029578/96390530-1d9abc00-1183-11eb-85f6-f9d41b82ab3b.png)

**Comment by sarru1291** [comment]
404 params use `navigator/navbar-2.html` partial. So, I think you can change the location of logo variable at the first two line in navabar-2 partial.

{{ $mainLogo:="assets/images/logo.svg" }}
{{ $invertedLogo:="assets/images/logo.svg" }}

**Comment by alex-bezek** [comment]
> 404 params use `navigator/navbar-2.html` partial. So, I think you can change the location of logo variable at the first two line in navabar-2 partial.
> 
> {{ $mainLogo:="assets/images/logo.svg" }}
> {{ $invertedLogo:="assets/images/logo.svg" }}

Thanks @sarru1291 , while that would work i'd have to override the whole partial correct (still pretty new to hugo but that seems to be how that would work)? I'd prefer to override as little of the internals of the theme as possible to make upgrading easier. I opened a PR here with what i think is a fix https://github.com/hossainemruz/toha/pull/104/files

**Comment by sarru1291** [comment]
>  I opened a PR here with what i think is a fix https://github.com/hossainemruz/toha/pull/104/files

That seems good. I removed the hard code and waiting for your fix to be merged.

**Comment by hossainemruz** [comment]
Fixed in #104
