### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by alex-bezek** [hossainemruz/toha#105]
To start, thank you for the wonderful open source theme. I just ported my blog over to hugo and chose your theme because it was beautiful and easy to work with. 

There are some defects I'd like to fix (I opened 1 pr so far here https://github.com/hossainemruz/toha/pull/104 ) and some enhancements around google lighthouse scores I'd like to make if you are open to them (I like for my sites too have as good of scores as possible in performance and accessibility). 

I noticed the repo https://github.com/hossainemruz/toha-example-site which it seems you are using for testing updates. You have a basic guide https://github.com/hossainemruz/toha#contributing but I thought it would be useful to document your normal local development lifecycle here as it took me some time to figure out how to work with the git submodule.

On a side note, I think it would be cool if you could add the hacktoberfest topic to the repo for this month
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Again, thank you for all you've done so far. Let me know if you have any guidance around contributing going forward.

**Comment by hossainemruz** [comment]
>some enhancements around google lighthouse scores I'd like to make if you are open to them (I like for my sites too have as good of scores as possible in performance and accessibility).

Sure. That would be great.

>I noticed the repo https://github.com/hossainemruz/toha-example-site which it seems you are using for testing updates. You have a basic guide https://github.com/hossainemruz/toha#contributing but I thought it would be useful to document your normal local development lifecycle here as it took me some time to figure out how to work with the git submodule.

Yes. I feel the need for a development guideline too. Unfortunately, I am not getting some free time to add one. Even the documentations are outdated. It would be great if you can send a PR.

>On a side note, I think it would be cool if you could add the hacktoberfest topic to the repo for this month

Done

**Comment by alex-bezek** [comment]
@hossainemruz I opened a PR here https://github.com/hossainemruz/toha/pull/110 with a stab at some documentation. Let me know what you think and if there are more details I should add. Thanks!
