### ISSUE TITLE
Site meta description not showing

### ISSUE THREAD

**Issue by sarru1291** [hossainemruz/toha#108]
![Screenshot from 2020-10-19 20-08-51](https://user-images.githubusercontent.com/22962336/96471696-3c658500-124d-11eb-912a-10e935883096.png)
As you can see, the content of meta-description is not showing, even though the description is given. In the index.html file, it's using `{{ .Site.Params.description }}`.

So, if we move the description param from `site.yaml` (currently placed here) to the `config.yaml` and it works.

**Comment by serverfriendsorg** [comment]
I can confirm it, but even if I place it in config.yaml it seems to have no effect. I using the theme with i18n support.

**Comment by sarru1291** [comment]
> I can confirm it, but even if I place it in config.yaml it seems to have no effect. I using the theme with i18n support.

Have you put the params in config.yaml like this? It worked for me.
<img width="494" alt="Screenshot 2020-10-20 at 7 49 21 AM" src="https://user-images.githubusercontent.com/22962336/96532134-de668b00-12a8-11eb-970e-11d118a92597.png">

**Comment by hossainemruz** [comment]
I can confirm this is a bug introduced after adding multi-language support. Will fix asap.

**Comment by alex-bezek** [comment]
@hossainemruz have you started on this or would you like me to take a stab at it?

**Comment by hossainemruz** [comment]
I haven't looked it yet. A PR will be appreciated.

**Comment by alex-bezek** [comment]
Sounds good, I've opened a PR here @hossainemruz  https://github.com/hossainemruz/toha/pull/121

**Comment by hossainemruz** [comment]
Should be fixed now. @sarru1291 Try pulling the master. Feel free to reopen if the issue persist.
