### ISSUE TITLE
About Section Author name missing

### ISSUE THREAD

**Issue by alex-bezek** [hossainemruz/toha#113]
In the about section card, there is a H3 element that should have the authors name but its empty
https://github.com/hossainemruz/toha/blob/master/layouts/partials/sections/about.html#L10
![image](https://user-images.githubusercontent.com/8029578/96673257-1a92fd80-1334-11eb-9079-58f28addbc60.png)

vs I'm assuming this is an older deployed version (perhaps prior to the localization efforts?)
![image](https://user-images.githubusercontent.com/8029578/96673327-43b38e00-1334-11eb-9208-ad2300a0258e.png)

I'm assuming you would want it to pull the name from this config https://github.com/hossainemruz/toha-example-site/blob/master/data/en/author.yaml#L2 . I tried updating the html to use https://github.com/hossainemruz/toha/blob/master/layouts/partials/helpers/get-author-name.html but it didn't seem to work so i must have been doing something wrong.

**Comment by hossainemruz** [comment]
Replace
```html
<h3 class="p-1">{{ site.Params.author.name }}</h3>
```
With
- add this at the top of the file
```html
{{ $author:= .Site.Data.author }}
{{ if (index .Site.Data .Site.Language.Lang).author }}
  {{ $author = (index .Site.Data .Site.Language.Lang).author }}
{{ end }}
```
- then update
```html
<h3 class="p-1">{{ $author.name }}</h3>
```

**Comment by alex-bezek** [comment]
Thanks!

I had to change it to 
```go
{{ $author:= site.Data.author }}
{{ if (index site.Data site.Language.Lang).author }}
  {{ $author = (index site.Data site.Language.Lang).author }}
{{ end }}
```
I think this the about is a section the `.` is the current context of that section, so `site` accesses the global site configs. I'm not quite sure best practices here around this context scoping and trying to use a partial to be dry vs just duplicating the logic to make things explicit and simple, so i'll defer to our judgement. 

I can open a PR with the above change if you'd like
![image](https://user-images.githubusercontent.com/8029578/96674571-1ae0c800-1337-11eb-9771-e87cc0441957.png)
![image](https://user-images.githubusercontent.com/8029578/96674598-26cc8a00-1337-11eb-964f-02ae1b959dfd.png)

**Comment by hossainemruz** [comment]
>I can open a PR with the above change if you'd like

Sure. Go on.

**Comment by alex-bezek** [comment]
PR opened here https://github.com/hossainemruz/toha/pull/114/files

**Comment by alex-bezek** [comment]
Now that the pr merged, my dependabot pulled in the changes and the diffs look good

https://github.com/alex-bezek/blog/pull/49
![image](https://user-images.githubusercontent.com/8029578/96677930-9bef8d80-133e-11eb-8d24-e48edbb7db80.png)
![image](https://user-images.githubusercontent.com/8029578/96678152-1b7d5c80-133f-11eb-8e5b-927e912b3ed5.png)

Closing this issue
