### ISSUE TITLE
How to add details in recent post sections

### ISSUE THREAD

**Issue by ahmadimt** [hossainemruz/toha#124]
### Question

In the exampleSite , I am unable to see any example to add recent posts. Can you please show some examples to add that?

**Comment by ranrinc** [comment]
@ahmadimt Please check hossainemruz template https://github.com/hossainemruz/toha-example-site

**Comment by ahmadimt** [comment]
Thanks for the reply @ranrinc . I checked the link provided but could not find any example there. It would be great if you please could share an example  here.

**Comment by ranrinc** [comment]
@ahmadimt when you say example do you mean the website made using toha? something like this? https://toha.netlify.app/

**Comment by ahmadimt** [comment]
I am able to get recent posts working
