### ISSUE TITLE
Allow project button shading to be removed

### ISSUE THREAD

**Issue by blueyetisoftware** [hossainemruz/toha#21]
I am trying to remove the shading that is covering the project buttons but have not been able to find it in the css. @hossainemruz Where can I find this shadow box over the top of the highlighted button?

<img width="440" alt="Screen Shot 2020-06-30 at 12 00 41 AM" src="https://user-images.githubusercontent.com/16869740/86100219-02d1f980-ba65-11ea-822a-81bccf701788.png">

**Comment by hossainemruz** [comment]
Its coming from bootstrap. I don't think it looks bad.
https://getbootstrap.com/docs/4.5/components/button-group/

**Comment by blueyetisoftware** [comment]
It doesn't look bad. I was just trying to modify it and couldn't find it. Thanks
