### ISSUE TITLE
add table of contents

### ISSUE THREAD

**Issue by GaHoWong** [hossainemruz/toha#34]
Is it possible to add an Easy-to-use and self-expanding table of contents, it is really useful！Example website：https://hugoloveit.com/theme-documentation-basics/

**Comment by hossainemruz** [comment]
Sure. I can add one. Just need some time.

**Comment by hossainemruz** [comment]
@GaHoWong I have added TOC in this PR: https://github.com/hossainemruz/toha/pull/33

Here, is what its going to look like: https://deploy-preview-3--toha.netlify.app/posts/writing-posts/markdown-syntax-guide/#code-blocks

Let me know if you have any comment.

**Comment by daveops1** [comment]
Just some quick feedback, some display issues on mobile devices.  I'm using a Samsing Galaxy S10+

[Image]

[Image]

Best,

David


________________________________

**Comment by hossainemruz** [comment]
@daveops1 The PR is still work in progress. I haven't fixed responsiveness yet.

**Comment by GaHoWong** [comment]
> 
> 
> @GaHoWong I have added TOC in this PR: #33
> 
> Here, is what its going to look like: https://deploy-preview-3--toha.netlify.app/posts/writing-posts/markdown-syntax-guide/#code-blocks
> 
> Let me know if you have any comment.

Great! But it seems that the area is too large, blocking part of the content, which is worth optimizing
