### ISSUE TITLE
Comma with a preceding space

### ISSUE THREAD

**Issue by kashifnazar** [hossainemruz/toha#36]
It's a very little issue but it should be fixed. In case both the start date and end date are specified, there is a space between the end date and the comma. Here is a screenshot.

![image](https://user-images.githubusercontent.com/1439263/87065273-42010700-c22a-11ea-8ebd-881593b58d53.png)
 
It's a one-liner fix in experience-info.html.

**Comment by hossainemruz** [comment]
@kashifnazar This PR should fix the issue: https://github.com/hossainemruz/toha/pull/37

**Comment by hossainemruz** [comment]
Try pulling the master

**Comment by kashifnazar** [comment]
Thanks for the rapid action.
