### ISSUE TITLE
Language attribute

### ISSUE THREAD

**Issue by imluxs** [hossainemruz/toha#38]
As a user in other countries，i think language attribute set by hugo variables will much better.

**Comment by hossainemruz** [comment]
Sure. I would love to add multi-language support. Just need to finish the basic functionalities first.

**Comment by imluxs** [comment]
Keep up the good work.

**Comment by cristian04** [comment]
I am also interested on this. Great work guys! I love the theme

**Comment by RalphPastel972** [comment]
I am also interested on this. Your work is awesome Hussain ! Thanks !

**Comment by Demmonius** [comment]
Hello @hossainemruz !

Like a lot of people, I would be interested in i18n and translations. Would you need some help in a PR? Or would you like to do it by your own?

Thank you for this beautiful template

**Comment by hossainemruz** [comment]
@Demmonius a PR will be great.
