### ISSUE TITLE
Menu breaks on mobile

### ISSUE THREAD

**Issue by itsyaoyu** [hossainemruz/toha#52]
Testing the [example site](https://toha.netlify.app/) on mobile, I discovered that you can't view all the menu options. Flagging this here.

![menu](https://user-images.githubusercontent.com/54951895/88325008-82fd1f00-ccf2-11ea-9782-8c15ad98293b.png)

**Comment by hossainemruz** [comment]
Which mobile are you using?

**Comment by itsyaoyu** [comment]
I am on iOS and tested this on Safari, Chrome, and Firefox.

**Comment by hossainemruz** [comment]
I don't own any iOS device. So, I couldn't test. Chrome debugging tool rendered properly for all iOS devices.

**Comment by itsyaoyu** [comment]
Hmm, I wonder if anyone else can replicate this issue?

**Comment by kcktilak** [comment]
I can confirm, the version in toha.netlify.app has issue in ios 13.5.1 (iPhone X)

**Comment by StefanTobler** [comment]
No problems for my site or the sample site on iOS 14.0, iPhone 8 Plus on safari and chrome, but I could replicate the issue on my girlfriends iPhone 11 in safari.

**Comment by hossainemruz** [comment]
I am not sure how I can fix something that I can't test. It will be great if someone can contribute the fix.

**Comment by cristian04** [comment]
I can reproduce on iPhone 8. Safari and chrome. Using iOS 13.6

**Comment by jeanmacena** [comment]
Chrome mobile simulator tool is not so great. I will try to check this out in the weekend and submit a PR.

**Comment by grahamguthrie99** [comment]
Same issue on iOS.. any update?

**Comment by jeanmacena** [comment]
Hello guys, 

Just a quickly update. I did a little change on the css and test it in my Iphone 6S Plus (safari and chrome) and now it looks ok. Tomorrow, after my job, I will test in my girlfriend's iPhone and iPad to check if it is working (I'm not sure if this happen on iPad too).

**Comment by hossainemruz** [comment]
I am able to reproduce this issue in webkit based [epiphany](https://github.com/GNOME/epiphany) browser.

**Comment by hossainemruz** [comment]
Fixed on #68
