### ISSUE TITLE
TOC in post page

### ISSUE THREAD

**Issue by Lattitude75** [hossainemruz/toha#55]
@hossainemruz I really like your website template and I used a slightly edited version of your design for my blog. Thank you very much for the great work!

Recently I have seen that you have changed the toha.netlify.app and I very much liked the implementation of toc on the posts page. So, I tried to clone your repository toha-example-site to see the change in code. Everything seems to work fine, but on the posts page, the sidebar, post and toc are misaligned. The sidelist on the left, them the post begins after the sidelist ends, and after that the toc shows up at the very end, even though the website on toha.netlify.app works fine. I do not know why.

I have also spent some time to edit the files to my liking, so I would not want to change it to your new organisational structure of config files as it would be a huge work. I just wanted to ask you if you could maybe provide the code additions to get the toc in the single.html without the sidebar. It would be very helpful, thanks!

**Comment by hossainemruz** [comment]
@Lattitude75 What browser are you using? Today, I am noticing some CSS issues in Firefox. There should be more issue on Safari.  Also, can you please share your device resolution? 

Btw, I have recently pushed some CSS fix. Can you make sure that you have the latest changes?

**Comment by Lattitude75** [comment]
I am using Brave one Linux and my resolution is 1366x768. Should I try the new changes in the toha-example-site now?

**Comment by hossainemruz** [comment]
I am also using Brave on Linux :P 

Try updating the theme. Navigate to `themes/toha` and pull the latest master.

Btw, does the https://toha.netlify.app/ woks properly on your device?

**Comment by Lattitude75** [comment]
I have cloned the toha-example-site repo and then used the theme from this [link](https://github.com/hossainemruz/toha/tree/629c7196a32c989b0bd0df731d2812be44c00a10). Previously, I just used to clone the toha-example-site directly and run `hugo server` directly. This does not seem to work properly now. The formatting errors are shown in the pictures.

And, yes the toha.netlify.app works properly.
![toha_1](https://user-images.githubusercontent.com/51109308/88477516-42094280-cf5e-11ea-814f-4dc6342246c2.png)
![toha_2](https://user-images.githubusercontent.com/51109308/88477518-42a1d900-cf5e-11ea-86ee-ee69c6f54942.png)

**Comment by hossainemruz** [comment]
Seems like CSS are not being applied properly. Did you have any custom CSS? Also, please try doing a hard reload (CTRL+SHIFT+R) of your browser window. I am suspecting its using the cached CSS.

**Comment by Lattitude75** [comment]
Okay, I tried that before too. But, now it worked. Also, is there a way to hide the sidebar in the posts? It would be better if the user can just expand it when needed, as the post seems narrowed down now.

**Comment by hossainemruz** [comment]
Currently, not possible. However, I have plan to support in future. https://github.com/hossainemruz/toha/issues/39

**Comment by Lattitude75** [comment]
Okay, that sounds great. Thank you, and keep up the great work!
