### ISSUE TITLE
Inconsistent Word-Spacing

### ISSUE THREAD

**Issue by StefanTobler** [hossainemruz/toha#56]
The word-spacing across the website seems to be inconsistent. Look at this skill for example. Some of the words are way more spaced out than others, yet they both only have one space between them.

![Screen Shot 2020-07-28 at 12 51 46 PM](https://user-images.githubusercontent.com/22108632/88696373-2d00f080-d0d1-11ea-9cc6-61844991243a.png)

![Screen Shot 2020-07-28 at 12 54 14 PM](https://user-images.githubusercontent.com/22108632/88696600-75b8a980-d0d1-11ea-9e5e-9706f5c0ebdd.png)

**Comment by hossainemruz** [comment]
This is intentional. It uses `text-align: justify `. Hence, the space between the words adjusted automatically to fill the line.

**Comment by StefanTobler** [comment]
For anyone looking at this in the future if you want consistent spacing change the following code in `style.css`.

```css
.card-body{
    text-align: left
}
```
