### ISSUE TITLE
Missing Google Analytics when set in config.yaml

### ISSUE THREAD

**Issue by oscarmrom** [hossainemruz/toha#58]
In the `config.yaml` you have a way to enable a Google Analytics Tracking ID. I set this but it wasn't showing up. I hardcoded it into the `header` partial of the theme for now. 

`config.yaml`
```yaml
  # Enable Google Analytics
  googleAnalytics: UA-XXXXXXXX
```

**Comment by StefanTobler** [comment]
Putting my google analytics UA in the `config.yaml` worked for me. People looking at my site show up in my analytics.

**Comment by oscarmrom** [comment]
Strange, I can't even find that snippet via the Chrome Dev Tools. It's not in the `<head>`

**Comment by hossainemruz** [comment]
@oscarmrom are you still facing this issue? If not, please close this.

**Comment by hossainemruz** [comment]
Feel free to reopen if you still feel this issue.
