### ISSUE TITLE
Invalid link to email address in about section

### ISSUE THREAD

**Issue by jbleduigou** [hossainemruz/toha#7]
Hi,

It seems that the link to the email address is not rendered properly.
See attached files for details.

**Comment by jbleduigou** [comment]
![image](https://user-images.githubusercontent.com/1489214/85622694-8788d600-b667-11ea-8003-c95f86722969.png)

![image](https://user-images.githubusercontent.com/1489214/85622713-8e174d80-b667-11ea-9ed3-02567c1487ff.png)

**Comment by hossainemruz** [comment]
Fixed in #8
