### ISSUE TITLE
Background image in low quality

### ISSUE THREAD

**Issue by cristian04** [hossainemruz/toha#70]
# Description

When browsing the website on Ipad or IPhone, the background image renders in low quality. (See attached screenshots)

# Steps to reproduce
1- Navigate to the site on iphone, ipad and desktop

# Expected Result
Background image must be adapted to the device's screen size

# Actual Result
Rendering a low quality image

# Versions

hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown

Theme: GIT HASH 61a9d7aea0ccf0acab225212b8e6f2be2e6fafa1

![Screen Shot 2020-08-19 at 00 51 04](https://user-images.githubusercontent.com/521587/90515067-33f1bf00-e1b6-11ea-9c04-e7f49af90b79.png)

![IMG_0209](https://user-images.githubusercontent.com/521587/90515254-7a471e00-e1b6-11ea-94c7-32ce00279816.jpeg)
![IMG_8423](https://user-images.githubusercontent.com/521587/90515263-7ddaa500-e1b6-11ea-8034-54a9842a301e.jpeg)

**Comment by hossainemruz** [comment]
That's strange. Chrome debugging tool rendering properly.

**Comment by cristian04** [comment]
Indeed. I dont know how to troubleshoot as I am not a webdeveloper :(

**Comment by HabibRh26** [comment]
I also faced the same, no matter How high res image I use , it gets blurred

**Comment by hossainemruz** [comment]
The blur is intentional. However, I believe its not properly rendering on Apple Devices. Please, try removing line 16-19 from here: https://github.com/hossainemruz/toha/blob/61a9d7aea0ccf0acab225212b8e6f2be2e6fafa1/static/assets/css/sections/home.css#L16

**Comment by cristian04** [comment]
> The blur is intentional. However, I believe its not properly rendering on Apple Devices. Please, try removing line 16-19 from here:
> 
> https://github.com/hossainemruz/toha/blob/61a9d7aea0ccf0acab225212b8e6f2be2e6fafa1/static/assets/css/sections/home.css#L16

This didn’t fix the issue, but I was able to find the cause for the weird behaviour:

 background-size: cover;

This property breaks the site on iPad and iPhones. Changing it causes the background image to be repeated on x and y.

Any advice to resolve this? I’m keen to provide a PR once is done. :)

**Comment by hossainemruz** [comment]
Add these lines. First is for Apple Devices. Second is for Mozila Firefox.
```css
-webkit-background-size: cover;
-moz-background-size: cover;
```

**Comment by cristian04** [comment]
> ```css
> -webkit-background-size: cover;
> -moz-background-size: cover;
> ```

It didnt fix it :( 

I was able to reproduce this on the Apple simulator. Im keen to share my screen if needed.

**Comment by hossainemruz** [comment]
I don't know how to fix it until I don't get access to any iOS device. :(

**Comment by hossainemruz** [comment]
Well, I guess I can use https://appetize.io/ to simulate a device. I can confirm the issue. Will fix ASAP.

**Comment by alex-bezek** [comment]
I can produce this issue using my iphone and mac paired together. The issue seems to be this https://stackoverflow.com/questions/24154666/background-size-cover-not-working-on-ios

> As @RyanKimber pointed out, fixed attached images use the whole <body> size. On mobile this can get really tall which blows your image out. Setting the attachment back to scroll allows your cover image to stretch within its own container.

Before
![image](https://user-images.githubusercontent.com/8029578/96672400-33021880-1332-11eb-98a6-461f0cf1c4db.png | width=200)

After changing background-attachment to scroll
![image](https://user-images.githubusercontent.com/8029578/96672524-7f4d5880-1332-11eb-9e10-893bdadd09da.png)

![image](https://user-images.githubusercontent.com/8029578/96672590-a60b8f00-1332-11eb-8d51-c42d21d19239.png | width=200)

**Comment by alex-bezek** [comment]
pr opened here https://github.com/hossainemruz/toha/pull/115/files
