### ISSUE TITLE
Skill cards style is wrong in Firefox

### ISSUE THREAD

**Issue by Conrix** [hossainemruz/toha#71]
# Description
When browsing the website on Firefox (Mac), Cards of Skill profile is not in shape. (See attached screenshots)

# Steps to reproduce
1- Navigate to the site with Firefox (https://toha.netlify.app/)
2- select skills menu.
3- Relead page (multiple times, some time skill cards are in shape sometime not)

# Expected Result
Skill cards have same height
Skill card has no large space below headline.

# Actual Result
Skill cards have different height
Skill card has large space below headline.

# Versions
hugo: v0.74.3/extended darwin/amd64
Theme: GIT HASH 5f48a5bacb8a13cecaef5b9d9fa7efe25d860f79
OS: Mac OS X 10.15.5
Firefox: 79.0 (64-Bit)
![Toha](https://user-images.githubusercontent.com/7335019/90519852-e0a54f80-e168-11ea-8b38-8015fe1907a8.png)

**Comment by hossainemruz** [comment]
Yes. I have also noticed the bug. Will fix ASAP. In the meantime, a PR will be greatly appreciated.

**Comment by hossainemruz** [comment]
@Conrix I have explained the reason why the skill cards height is unequal sometime. It should not be noticeable in normal operation. Please close the issue if the initial issue no longer persist.

**Comment by alex-bezek** [comment]
@hossainemruz I've tested as well in firefox
![image](https://user-images.githubusercontent.com/8029578/97067002-2de9d700-1587-11eb-89a4-4ee26872182b.png)

and things seem fine. I think you can close this unless @Conrix has any more concerns
