### ISSUE TITLE
Clicking on top Menu tabs shows #NaN bookmark

### ISSUE THREAD

**Issue by philshem** [hossainemruz/toha#72]
Visiting the demo site https://toha.netlify.app/ (and also my site under development), 

when I click on one of the top menu links

<img width="442" alt="image" src="https://user-images.githubusercontent.com/4997607/90615193-0fc0cd00-e20c-11ea-89ec-e0d80f24fa42.png">

I go to the correct bookmark on the page, but the URL in the browser shows #NaN

<img width="435" alt="image" src="https://user-images.githubusercontent.com/4997607/90615250-223b0680-e20c-11ea-8ef3-6e268f176fb9.png">

https://toha.netlify.app/#NaN

Would be cool to show either nothing, or the section name, after the `#`

**Comment by HabibRh26** [comment]
> Visiting the demo site https://toha.netlify.app/ (and also my site under development),
> 
> when I click on one of the top menu links
> 
> <img alt="image" width="442" src="https://user-images.githubusercontent.com/4997607/90615193-0fc0cd00-e20c-11ea-89ec-e0d80f24fa42.png">
> 
> I go to the correct bookmark on the page, but the URL in the browser shows #NaN
> 
> <img alt="image" width="435" src="https://user-images.githubusercontent.com/4997607/90615250-223b0680-e20c-11ea-8ef3-6e268f176fb9.png">
> 
> https://toha.netlify.app/#NaN
> 
> Would be cool to show either nothing, or the section name, after the `#`

Did you deploy your site on netlify? I deployed on GitHub but `posts` section is not working, just want  to know whether it is okay in netlify or not? thanks

**Comment by philshem** [comment]
No, my site was hosted locally: `hugo server -w`

**Comment by hossainemruz** [comment]
@philshem this issue should be fixed by #73
