### ISSUE TITLE
Blog post handling issue

### ISSUE THREAD

**Issue by HabibRh26** [hossainemruz/toha#78]
I tried to add another folder named `Website` in my blog section but somehow I am not getting the mistake. 
Problem is the file named ``Website Domain`` is not showing inside the ``Website`` directory, rather It is displaying outside, and 
![main](https://user-images.githubusercontent.com/47397271/90984052-69baed00-e594-11ea-8d8b-e313dbb593a8.png)
when I click the ``Website`` directory nothing happens. How can I include the ``Website Domain`` file inside the ``Website`` directory like the ``GitHub`` folder. </br>
Here is the condition of my relative files-- </br>
![menu1_index](https://user-images.githubusercontent.com/47397271/90984259-ac30f980-e595-11ea-989e-529f5c18ea57.png)
and </br>
![menu2_index](https://user-images.githubusercontent.com/47397271/90984343-147fdb00-e596-11ea-972e-e1117bf4fdd9.png)
and </br>
![menu2_md](https://user-images.githubusercontent.com/47397271/90984361-30837c80-e596-11ea-9be1-86a0cf261edd.png)

**Comment by ghostcodekc** [comment]
Hi @HabibRh26 ,

Your folder structure is correct, however your _index.md and post.md are not. Please use the below code as reference.

Try the following code: 
[/Website/_index.md](https://pastebin.com/VEYwB9t9)
```
---
title: Website Domain
menu:
  sidebar:
    name: Website Domain
    identifier: website-domain
    weight: 500
---
```

[/Website/example-post-1.md](https://pastebin.com/Un2BDNKs)
```
---
title: "Example Post 1"
date: 2020-06-08T06:20:50+06:00
hero: /images/posts/configuration/about-section-hero.svg
menu:
  sidebar:
    name: Custom Domain to Github
    identifier: website-domain-test
    parent: website-domain
    weight: 501
---

## Introduction

> This post is going to show you how to get a custom domain to github

# Step 1

- TESTING WEBSITE DOMAIN
```

**Comment by HabibRh26** [comment]
> Hi @HabibRh26 ,
> 
> Your folder structure is correct, however your _index.md and post.md are not. Please use the below code as reference.
> 
> Try the following code:
> [/Website/_index.md](https://pastebin.com/VEYwB9t9)
> 
> ```
> ---
> title: Website Domain
> menu:
>   sidebar:
>     name: Website Domain
>     identifier: website-domain
>     weight: 500
> ---
> ```
> 
> [/Website/example-post-1.md](https://pastebin.com/Un2BDNKs)
> 
> ```
> ---
> title: "Example Post 1"
> date: 2020-06-08T06:20:50+06:00
> hero: /images/posts/configuration/about-section-hero.svg
> menu:
>   sidebar:
>     name: Custom Domain to Github
>     identifier: website-domain-test
>     parent: website-domain
>     weight: 501
> ---
> 
> ## Introduction
> 
> > This post is going to show you how to get a custom domain to github
> 
> # Step 1
> 
> - TESTING WEBSITE DOMAIN
> ```
> 
> If this resolves your issue, please mark this issue as closed.
> 
> Thank you,
> Andrew

Thanks a lot. I am closing the issue. But before that one more problem, I'm trying to use the backtick but It is not working for some texts in the blog post. In the image no 1 is okay but other boxes are not rendering the proper output. </br>
markdown file </br>
![gitProb](https://user-images.githubusercontent.com/47397271/91221567-a24afa00-e73f-11ea-9026-5ba69bee877d.png)
</br>
the output below: </br>
![pic](https://user-images.githubusercontent.com/47397271/91221629-bdb60500-e73f-11ea-978a-f94db135d76c.png)

**Comment by ghostcodekc** [comment]
@HabibRh26 ,

The backtick (also known as the grave accent or backquote) is used to start a code section in Markdown. I would suggest brushing up on markdown at the following links:
[markdown-it demo](https://markdown-it.github.io/)
[markdown quick reference](https://wordpress.com/support/markdown-quick-reference/)
[Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

Thank you,
Andrew
