### ISSUE TITLE
Navbar collapse Misalignment

### ISSUE THREAD

**Issue by sarru1291** [hossainemruz/toha#79]
Navbar collapse working all fine on all web emulated devices and on my other personal mobile as well. 

But this is the scene on my Samsung J2 2016 model and Safari web browser.

![WhatsApp Image 2020-08-24 at 11 04 05 AM](https://user-images.githubusercontent.com/22962336/91007601-09f72d00-e5fa-11ea-9733-b559ec2bb46a.jpeg)

![untitled (1)](https://user-images.githubusercontent.com/22962336/91008516-301dcc80-e5fc-11ea-9be8-834af6f204ac.png)

**Comment by hossainemruz** [comment]
We are already working on the issue in  this PR: https://github.com/hossainemruz/toha/pull/68

**Comment by hossainemruz** [comment]
@sarru1291 This issue should be fixed by #68. Can you please confirm?

**Comment by sarru1291** [comment]
Yes, I can confirm it's working now. Thank you.
