### ISSUE TITLE
Header posts are 404

### ISSUE THREAD

**Issue by haxifang-aircos** [hossainemruz/toha#84]
Hello, I created a new article locally using the following command：
`hugo new about.md`

Then execute the following command
`hugo server -w`

On my page, the posts module is 404, and the recent posts did not show the article I just made.

May I ask where did the wrong operation happen?

My website path: https://gongguowei.com/

Attach pictures:
![image](https://user-images.githubusercontent.com/61681123/92300295-3f9dfd80-ef8c-11ea-85a0-3af5d72628e3.png)

![image](https://user-images.githubusercontent.com/61681123/92300307-580e1800-ef8c-11ea-8001-e4f74716c1bb.png)

**Comment by HabibRh26** [comment]
> Hello, I created a new article locally using the following command：
> `hugo new about.md`
> 
> Then execute the following command
> `hugo server -w`
> 
> On my page, the posts module is 404, and the recent posts did not show the article I just made.
> 
> May I ask where did the wrong operation happen?
> 
> My website path: https://gongguowei.com/
> 
> Attach pictures:
> ![image](https://user-images.githubusercontent.com/61681123/92300295-3f9dfd80-ef8c-11ea-85a0-3af5d72628e3.png)
> 
> ![image](https://user-images.githubusercontent.com/61681123/92300307-580e1800-ef8c-11ea-8001-e4f74716c1bb.png)

make sure you follow the exact instruction, check the first comment --- </br>
https://toha.netlify.app/posts/writing-posts/category/creating-category/

**Comment by haxifang-aircos** [comment]
> > Hello, I created a new article locally using the following command：
> > `hugo new about.md`
> > Then execute the following command
> > `hugo server -w`
> > On my page, the posts module is 404, and the recent posts did not show the article I just made.
> > May I ask where did the wrong operation happen?
> > My website path: https://gongguowei.com/
> > Attach pictures:
> > ![image](https://user-images.githubusercontent.com/61681123/92300295-3f9dfd80-ef8c-11ea-85a0-3af5d72628e3.png)
> > ![image](https://user-images.githubusercontent.com/61681123/92300307-580e1800-ef8c-11ea-8001-e4f74716c1bb.png)
> 
> make sure you follow the exact instruction, check the first comment ---
> 
> https://toha.netlify.app/posts/writing-posts/category/creating-category/

Sorry, I did not find the method to create the article in the link above.

**Comment by HabibRh26** [comment]
create a folder named `content`, then inside this create another folder called `posts`, then inside this create a file named `_index.md`, then follow the above mentioned link for what should you write inside the markdown or how should you write

**Comment by haxifang-aircos** [comment]
> create a folder named `content`, then inside this create another folder called `posts`, then inside this create a file named `_index.md`, then follow the above mentioned link for what should you write inside the markdown or how should you write

thank you very much!
