### ISSUE TITLE
How to remove improve this page and disqus from posts

### ISSUE THREAD

**Issue by dabymartinez** [hossainemruz/toha#86]
How do I remove the "improve this page" and "comments powered by disqus" from posts?
![Screen Shot 2020-09-12 at 1 10 10 PM](https://user-images.githubusercontent.com/70119578/93000970-9f028d00-f4f9-11ea-9525-feaecf682d38.png)

**Comment by hossainemruz** [comment]
Just remove [disqusShortname](https://github.com/hossainemruz/toha/blob/6c2cca012758803802a81d06dccb60c2d2d48b66/exampleSite/config.yaml#L20) and [gitRepo](https://github.com/hossainemruz/toha/blob/6c2cca012758803802a81d06dccb60c2d2d48b66/exampleSite/config.yaml#L45) under `params` section from your `config.yaml`.

**Comment by dabymartinez** [comment]
Thank you!
